spring.application.name=elm-employee-service

# Database connection (SQL Server Authentication)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=EmployeeDB;encrypt=false;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=YourStrongPassword123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

# Runs on dynamically allocated port - by Eureka
server.port=0
spring.test.database.replace=none

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true




# Explicitly enable logging to a file
logging.file.name=C:/Work/Java/elm-employee-service/elm-employee-serviceLOG.log

# Enable detailed Eureka logs
logging.level.root=INFO
logging.level.com.netflix.eureka=DEBUG
logging.level.com.netflix.discovery=DEBUG
logging.level.org.springframework.cloud=DEBUG

# Force logs to be written immediately (important for debugging)
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=5


management.endpoints.web.exposure.include=*
management.endpoint.mappings.enabled=true
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator


logging.level.org.springframework=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.example=DEBUG
logging.level.org.springframework.security=DEBUG


spring.main.allow-bean-definition-overriding=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

# Connect to Auth Service to validate JWTs dynamically
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8082/auth/.well-known/jwks.json
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082







