package com.example.shared.event;

public enum EventType {
    EMPLOYEE_CREATED,
    EMPLOYEE_UPDATED,
    EMPLOYEE_DELETED,
    AUTH_USER_CREATED,
    AUTH_USER_UPDATED,
    AUTH_USER_DELETED,
    // ➕ New leave events
    LEAVE_REQUESTED,
    LEAVE_APPROVED,
    LEAVE_REJECTED,
    LEAVE_CANCELLED,
    
    LEAVE_BALANCE_INITIALIZED,
    LEAVE_BALANCE_UPDATED


}
