spring.application.name=elm-notification-service


server.port=8085

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true


# Logging to file
logging.file.name=logs/notification-service.log
logging.level.root=INFO
logging.level.com.example=DEBUG

# redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
redis.ttl.minutes=10


# === MAIL CONFIG ===
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=2b4a8d6286b634
spring.mail.password=071a11857203b2
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

