server.port=8082
spring.application.name=elm-auth-service

# Database (SQL Server)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=AuthDB;encrypt=false;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=YourStrongPassword123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# JWT Settings
auth.jwt.secret=MySuperStrongSecretKeyForJWTValidation1234567890123456
# 10 00000 hours
auth.jwt.expiration=3600000000000  

# Enable logging to a file
logging.file.name=auth-service.log
logging.level.root=DEBUG
logging.level.com.example=DEBUG
logging.level.org.springframework=DEBUG

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8082/.well-known/jwks.json

management.endpoints.web.exposure.include=*



