#server.port=8082
#server.port=0
server.port=8082
server.address=0.0.0.0
server.servlet.context-path=/
spring.main.web-application-type=servlet

spring.application.name=elm-auth-service

# Database (SQL Server)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=AuthDB;encrypt=false;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=YourStrongPassword123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
# Improve Eureka stability
eureka.client.initial-instance-info-replication-interval-seconds=30
eureka.client.registry-fetch-interval-seconds=10
eureka.instance.leaseRenewalIntervalInSeconds=10
eureka.instance.leaseExpirationDurationInSeconds=30

# JWT Settings
auth.jwt.secret=MySuperStrongSecretKeyForJWTValidation1234567890123456
# 10 00000 hours
auth.jwt.expiration=3600000000000  

# Enable logging to a file
logging.file.name=auth-service.log
logging.level.root=DEBUG
logging.level.com.example=DEBUG
logging.level.org.springframework=DEBUG

#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8082/.well-known/jwks.json

#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://${eureka.instance.hostname}:${server.port}/.well-known/jwks.json
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://${eureka.instance.ip-address}:${server.port}/.well-known/jwks.json
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://${eureka.instance.instance-id}:${server.port}/.well-known/jwks.json




management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
logging.level.org.springframework.web=DEBUG


logging.level.org.springframework.security=DEBUG



#auth.jwt.private-key=-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkq...\n-----END PRIVATE KEY-----
#auth.jwt.public-key=-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9...\n-----END PUBLIC KEY-----
auth.jwt.private-key=-----BEGIN PRIVATE KEY-----MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDKprhjxKNpXW1ECvqyK2e8kprAGvVEuFzIbDO1+szzvim6Pz+erznnCNaJPKvwA5gpE0RBBEewQ2/+hB6UXMpkS1t3TbUOwALpohtHqDgSarlCpe5NhKffz2CewYOI0KMczpdoFMLc/Vxa6roC3Gm+3KMmSbKUGDdz27UNwwJwsGWu6xXJ18r6tG/WCqGd3pH3QMZBZT3KieBEcc+x5Ru/VWOcRELIlWNp7P7KtiBKqWPWdcmM+Xqhlj5AS/qqjyS1J7JlUO9D90zlZVxqrLsI5xXBJ9AhTWknnXzwPXW5/WEzKdI5KJqoYoUULpmWYs2hrvlsaxD1LB3aGtm91B9hAgMBAAECggEAAs/88baFjDrC6ig1rzzAD3C17i9ZmCWaX7Y1DVl2GCEQysV3XFw4c0ru5kqbJMU6AAJE/DAt5LB6Pg0m8FPC2SY8wQYT2pOX3sFJvA0lvRIHMO7Pr4/6dUuB9DtsOB0pfFwneLHGvA2AnKroCrjfd1SFfPcrdS0fsjoPqX7wulq0BKAw57xCqLNAGOc3erW3GAoDb2AavOC/UI+Yhf2xpQw7cpmvBR2/I6g0QPd+KbLeJj4gcrZJN6IlpeG53MbTzr7Z7ilkTDnmuSCDDl6bNpBlDpjRD5Fm9xo5Pxoioa0HilCl2+OsLjwr0sJUIvM1thnPsaswVD49SJvSicBO6QKBgQD5nk0a+3QXrIDJ/V1EOygBRkZk88ch6a7E3kcKJ8Z3R4SWxLA0HWvHMIX5+/pSDn/uS6ZPfbrPi+h/vceE80hnAZA4H1aCrw9BDbeddsfyzVkCNmzu2rlocoqSNCpWxruhKhXv4qRIY8D0+wuNGiAHLB42G8MiNAbTUx8jQ4pPqQKBgQDP1QeExxhhfmFlLz5TlyCXHeWAKoeMaKosKi68OhatLBQqEHp+HOcvHXPxs8Xj1IFpUIRv9er3JgqkCGAnMA0xnogBpvTLbJD+1CclAPWWfsUsXxSfGDfKqmVGYCoKg/DZ/D3g2Y0h6wcVVKiAi2i9G2jgc6wStO4GBc9aa14E+QKBgBFvz28NFaT5td1mR3eWskq0gAJZTRW/Xyf9ZvT8pk56vnZRswVQ8NBvQUyfH3NP8/vPaQSwgbYxzcHundtZqzsWzt48wixK0kP3E1Z6j6kUUx1mc+GTgdQb/DYOUs7Q/xZY/ENPj65G2ZnDV6E5q/cUS9/3vH/NJpTof4pVE3pRAoGAHj5w7qiOarmacMAUQNPQQU1vdVw7B3q/sNeen3OQkzjD4m8tdCa+mcOeeMDhfksRXgMCksxlmfumNsKlQ26hrOPWBO+H1gaBfyPeYmsmUfU2ukNH2/MJQ2vSexBJbehPZ1lmo87k09fA2yDLuJEQ99wCQg9zLfG4ZZX4276eGvkCgYBfEwLKJ55M2vnK8t3ZwfLg13FOUGnQkq8qODsveG9Ldh2RprzBP8/NFItYE4snMm0tM/2M+RkQ+7gdqQ6q3RcQZGzFhK1pd9U4eSzOLrsU4hd7wPflXoNeUAPkmZoejjrf2TMtZjvVgNjsLKf5Gz0B1iL/neBvts2qqEVkTPXDoA==-----END PRIVATE KEY-----
auth.jwt.public-key=-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyqa4Y8SjaV1tRAr6sitnvJKawBr1RLhcyGwztfrM874puj8/nq855wjWiTyr8AOYKRNEQQRHsENv/oQelFzKZEtbd021DsAC6aIbR6g4Emq5QqXuTYSn389gnsGDiNCjHM6XaBTC3P1cWuq6AtxpvtyjJkmylBg3c9u1DcMCcLBlrusVydfK+rRv1gqhnd6R90DGQWU9yongRHHPseUbv1VjnERCyJVjaez+yrYgSqlj1nXJjPl6oZY+QEv6qo8ktSeyZVDvQ/dM5WVcaqy7COcVwSfQIU1pJ5188D11uf1hMynSOSiaqGKFFC6ZlmLNoa75bGsQ9Swd2hrZvdQfYQIDAQAB-----END PUBLIC KEY-----


spring.security.oauth2.resourceserver.jwt.public-key=-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyqa4Y8SjaV1tRAr6sitnvJKawBr1RLhcyGwztfrM874puj8/nq855wjWiTyr8AOYKRNEQQRHsENv/oQelFzKZEtbd021DsAC6aIbR6g4Emq5QqXuTYSn389gnsGDiNCjHM6XaBTC3P1cWuq6AtxpvtyjJkmylBg3c9u1DcMCcLBlrusVydfK+rRv1gqhnd6R90DGQWU9yongRHHPseUbv1VjnERCyJVjaez+yrYgSqlj1nXJjPl6oZY+QEv6qo8ktSeyZVDvQ/dM5WVcaqy7COcVwSfQIU1pJ5188D11uf1hMynSOSiaqGKFFC6ZlmLNoa75bGsQ9Swd2hrZvdQfYQIDAQAB-----END PUBLIC KEY-----




