server.port=8761
spring.application.name=elm-eureka-server

# Eureka Server Settings
eureka.server.enable-self-preservation=true
eureka.server.expected-client-renewal-interval-seconds=30
eureka.dashboard.show-all=true

# Fix Instance Information
eureka.instance.instance-id=${spring.application.name}:${random.int}
eureka.instance.hostname=localhost

# Security Credentials (if needed)
spring.security.user.name=admin
spring.security.user.password=admin123
