spring.application.name=elm-api-gateway
server.port=8080

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Ensure API Gateway waits before trying to register
eureka.client.initial-instance-info-replication-interval-seconds=30
eureka.client.registry-fetch-interval-seconds=10

# API Gateway Service Registration
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.metadata-map.zone=default
eureka.instance.leaseRenewalIntervalInSeconds=10
eureka.instance.leaseExpirationDurationInSeconds=30
eureka.instance.statusPageUrl=http://localhost:${server.port}/actuator/info
eureka.instance.healthCheckUrl=http://localhost:${server.port}/actuator/health

# Enable Eureka-based Dynamic Routing
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Manually define route for Employee Service
spring.cloud.gateway.routes[0].id=employee-service
spring.cloud.gateway.routes[0].uri=lb://ELM-EMPLOYEE-SERVICE
spring.cloud.gateway.routes[0].predicates=Path=/employees/**
#spring.cloud.gateway.routes[0].filters=RemoveRequestHeader=Cookie, PreserveHostHeader
spring.cloud.gateway.routes[0].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.routes[0].filters[1]=PreserveHostHeader
spring.cloud.gateway.routes[0].filters[2]=CircuitBreaker=name=employeeCircuitBreaker,fallbackUri=forward:/fallback/employees



# Manually define route for Auth Service
spring.cloud.gateway.routes[1].id=auth-service
spring.cloud.gateway.routes[1].uri=lb://ELM-AUTH-SERVICE
spring.cloud.gateway.routes[1].predicates=Path=/auth/**
#spring.cloud.gateway.routes[1].filters=RemoveRequestHeader=Cookie, PreserveHostHeader
spring.cloud.gateway.routes[1].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.routes[1].filters[1]=PreserveHostHeader
spring.cloud.gateway.routes[1].filters[2]=CircuitBreaker=name=authCB,fallbackUri=forward:/fallback/auth

# Circuit breaker config for auth
resilience4j.circuitbreaker.instances.authCB.slidingWindowSize=5
resilience4j.circuitbreaker.instances.authCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.authCB.minimumNumberOfCalls=2
resilience4j.circuitbreaker.instances.authCB.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.authCB.waitDurationInOpenState=10s



# Manually define route for Leave Service
spring.cloud.gateway.routes[2].id=leave-service
spring.cloud.gateway.routes[2].uri=lb://ELM-LEAVE-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/leave/**
spring.cloud.gateway.routes[2].predicates[1]=Path=/leave-requests/**
spring.cloud.gateway.routes[2].predicates[2]=Path=/leave-balances/**
spring.cloud.gateway.routes[2].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.routes[2].filters[1]=PreserveHostHeader
spring.cloud.gateway.routes[2].filters[2]=CircuitBreaker=name=leaveCB,fallbackUri=forward:/fallback/leave


# Circuit breaker config for leave
resilience4j.circuitbreaker.instances.leaveCB.slidingWindowSize=5
resilience4j.circuitbreaker.instances.leaveCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.leaveCB.minimumNumberOfCalls=2
resilience4j.circuitbreaker.instances.leaveCB.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.leaveCB.waitDurationInOpenState=10s

resilience4j.timelimiter.instances.leaveCB.timeoutDuration=1s
resilience4j.timelimiter.instances.leaveCB.cancelRunningFuture=true


# Timeout settings are required for fallback to trigger
resilience4j.timelimiter.instances.authCB.timeoutDuration=1s
resilience4j.timelimiter.instances.authCB.cancelRunningFuture=true


# Logging Configuration
logging.file.name=logs/api-gateway.log
logging.level.root=INFO
logging.level.com.netflix.discovery=TRACE
logging.level.org.springframework.cloud=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG

spring.main.web-application-type=reactive

management.endpoints.web.exposure.include=*
management.endpoint.gateway.enabled=true
management.endpoint.health.show-details=always

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8082/auth/.well-known/jwks.json



resilience4j.circuitbreaker.instances.authCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.authCircuitBreaker.slidingWindowSize=5
resilience4j.circuitbreaker.instances.authCircuitBreaker.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.authCircuitBreaker.minimumNumberOfCalls=2
resilience4j.circuitbreaker.instances.authCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.authCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.authCircuitBreaker.eventConsumerBufferSize=10
resilience4j.circuitbreaker.instances.authCircuitBreaker.slowCallDurationThreshold=1s
resilience4j.circuitbreaker.instances.authCircuitBreaker.slowCallRateThreshold=100

# Fallback must trigger after timeout
resilience4j.timelimiter.instances.authCircuitBreaker.timeoutDuration=1s
resilience4j.timelimiter.instances.authCircuitBreaker.cancelRunningFuture=true


#kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer




