spring.application.name=elm-leave-service

# Server Port
server.port=8084

# SQL Server DB
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=LeaveDB;encrypt=false;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=YourStrongPassword123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Logging
logging.file.name=leave-service.log
logging.level.root=INFO
logging.level.com.example=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# JWT Validation (via AuthService)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8082/auth/.well-known/jwks.json

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
