# Application Name
spring.application.name=elm-api-gateway
server.port=8080

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Ensure API Gateway waits before trying to register
eureka.client.initial-instance-info-replication-interval-seconds=30
eureka.client.registry-fetch-interval-seconds=10

# Force API Gateway to use its real hostname (avoid IP conflicts)
eureka.instance.hostname=localhost
#eureka.instance.prefer-ip-address=true
eureka.instance.prefer-ip-address=false
# Set Metadata (Prevents Eureka from rejecting API Gateway)
eureka.instance.metadata-map.zone=default

# Set Metadata to Avoid Registration Conflicts
eureka.instance.leaseRenewalIntervalInSeconds=10
eureka.instance.leaseExpirationDurationInSeconds=30
eureka.instance.statusPageUrl=http://localhost:${server.port}/actuator/info
eureka.instance.healthCheckUrl=http://localhost:${server.port}/actuator/health

# Management Endpoints
management.endpoints.web.exposure.include=info,health

# Logging Configuration
logging.file.name=logs/api-gateway.log
logging.level.root=INFO
logging.level.com.netflix.discovery=TRACE
logging.level.org.springframework.cloud=DEBUG


spring.main.web-application-type=reactive




