#server.port=8082
#server.port=0
server.port=8082
server.address=0.0.0.0
server.servlet.context-path=/
spring.main.web-application-type=servlet

spring.application.name=elm-auth-service

# Database (SQL Server)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=AuthDB;encrypt=false;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=YourStrongPassword123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
# Improve Eureka stability
eureka.client.initial-instance-info-replication-interval-seconds=30
eureka.client.registry-fetch-interval-seconds=10
eureka.instance.leaseRenewalIntervalInSeconds=10
eureka.instance.leaseExpirationDurationInSeconds=30

# JWT Settings
auth.jwt.secret=MySuperStrongSecretKeyForJWTValidation1234567890123456
# 10 00000 hours
auth.jwt.expiration=3600000000000  

# Enable logging to a file
logging.file.name=auth-service.log
logging.level.root=DEBUG
logging.level.com.example=DEBUG
logging.level.org.springframework=DEBUG

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8082/.well-known/jwks.json

#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://${eureka.instance.hostname}:${server.port}/.well-known/jwks.json
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://${eureka.instance.ip-address}:${server.port}/.well-known/jwks.json
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://${eureka.instance.instance-id}:${server.port}/.well-known/jwks.json




management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
logging.level.org.springframework.web=DEBUG


logging.level.org.springframework.security=DEBUG



#auth.jwt.private-key=-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkq...\n-----END PRIVATE KEY-----
#auth.jwt.public-key=-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9...\n-----END PUBLIC KEY-----
auth.jwt.private-key=-----BEGIN RSA PRIVATE KEY-----MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDWMl5/8PxhtWWDa6Bf+qJvpF5I97IhYhqW8ey2d9N7Wr+pU7IfFupMsF/7sQtwNUeXf6kvMuM6JImZ+M13id3ooBw4H/xltHQQC4DzAWqywqU+ePVdmXD566qYxNwLbYqNFqHJjyERn3EwXy9E/XEO99WHZTZLUs5PLaVMbcATEd8DeOehwCC3JSYBxJ5FE/WvCMWfvaXqj4ByGrOJ7b0PMrH8yJRAKEvDDyzoYpbUMVGmtGX3xze+m4xvsS7BUJ1FB2B182ptKXwABK7CkVzEW1poh2OJmtNynlCAW41zkdPWQJoY8TF7xYcy9j4MfaHFU2U4yIyz0Y/ZdkSMJJohAgMBAAECggEADO72dpjUhHA+Wu5RI4dJiGtowTsqASRtVDDAPE+FiezaDQPF8GUJbLjRphInDXVwhzaCi4KlGcoPACiq/DOehJqP8z7RlkqMUroYsfoJ7Hu4T2Qtj9Z61EkyM3Tfj7xJ7pvJO34HxYqjfDcJiAu0Ae73cIXgZP5XZ4yE1W9jEHbNcqlgI/rDWDtb4cZpce1A/XfBFwivN0jDkCs1W/8jwtTo7APBPpEdcvwMTRgiEdds2FYoQx/QAd3Q+05tJxDFtVU/5sonI7tvhDf1rW/6Q8VU4p1x+vTdPy3SulgSa4FjunGSR5LtXBsXZcDhzU/SoZ1qH2vMU++eXvxbWrMWKQKBgQD5oWwcjoKG3cKicK9NyAaMIOtvhjNvRf+/GfopXZAtKkxBosRY92uBWEfUjVSleJKrtpkOmWlSkzT9uLX8YygBIzu2coUU+UH6CqMw3/um2IHmg3AzOhSq4m6TZHEA93WjMCwuoK5nBXiXfwpna8o6hymAw3fpH4LlumCdU8330wKBgQDbqX6ZgsoG2xlTpaLpUkIxkAh4J43LTrquky4T96XaFcOZQUKkjm0xPtINeMJH+C6BT8lTF/oRDTa1QB2BdF2owMx9bMxSvjy+Mkby4zppDq4RBdRPah9jYOr2xx4frInAJZg3OlZLG12ouDl/b5xZxX8seKiB2mKlwslR/axBuwKBgQDbEii4nvA5v1/SAqY10na8fx9ezh1RZ9LbOMbrimq+2EH30AoUMX4tEvZmuGkyli/Rdfu4bjWZ/AojJ/i9t58h8HO016enEmAuOSuh9s74S0UksPDEZBJDLVfxDdKGEKUyQ1Ji0Sx8yLZd7WWKAXSGDJwFnoUbF0ZeqUOkjilRdQKBgQDTbwBm7tdbZgWo2CRJhV4lqsgcL6ZybWOPqieOHK/NjWlq2MA2+Mjtv9QcF4KaF69b1NqqWsffJeLk78P22XVVe87ZY6IAexCo2mgkXsfYW8L8q6nCjxmLZLyFsP+z6TXmd8leT47EWKD8R+dAXMQYPNu+iJ1Z8EVH3Ig/nXbzBQKBgHgvWvFbTH3f1iLssnzZ13bQUwo8d8R4OmAo2hjSc/thgua2uEEApatpGtue+TgBYsR0BZuj8X5jPLktRErLmUMm7LwGy2gf+x5CEPTuZMOukxKzYVsgVtYEyW745QSKXvOFJF4msABGxJVHtzxTmu/IgwagYkRdpgpI1zMcLAhG-----END RSA PRIVATE KEY-----
auth.jwt.public-key=-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1jJef/D8YbVlg2ugX/qib6ReSPeyIWIalvHstnfTe1q/qVOyHxbqTLBf+7ELcDVHl3+pLzLjOiSJmfjNd4nd6KAcOB/8ZbR0EAuA8wFqssKlPnj1XZlw+euqmMTcC22KjRahyY8hEZ9xMF8vRP1xDvfVh2U2S1LOTy2lTG3AExHfA3jnocAgtyUmAcSeRRP1rwjFn72l6o+Achqzie29DzKx/MiUQChLww8s6GKW1DFRprRl98c3vpuMb7EuwVCdRQdgdfNqbSl8AASuwpFcxFtaaIdjiZrTcp5QgFuNc5HT1kCaGPExe8WHMvY+DH2hxVNlOMiMs9GP2XZEjCSaIQIDAQAB-----END PUBLIC KEY-----




